### ISSUE TITLE
Error Webpage

### ISSUE THREAD

**Issue by Faizi5807** [Faizi5807/SQE-Project#1]
In the login page , when an invalid username or password is entered the system proceeds to an Error Webpage instead of showing a wrong input message. 
Reference :
Test Case 1.2

**Comment by Maryamraeesalvi01** [comment]
In the add to cart panel ,when profile button is clicked ,it doesn't proceed to profile rather an error webpage opens.
Reference :
Test Case 3.3

**Comment by Maryamraeesalvi01** [comment]
When the admin login panel triggers an invalid input, the system proceeds to white label error page.
Reference :
Test Case 4.2

**Comment by Maryamraeesalvi01** [comment]
When admin had  logged in after valid login credentials and user clicks Homepage button it triggers an error webpage.
Reference:
Test Case 5.5

**Comment by faiq101** [comment]
When admin opens category and clicks delete to delete a category it triggers error webpage.
Reference Test Case : 6.1

**Comment by faiq101** [comment]
When user clicks logout to exit the manage category section it displays error webpage error. 
Reference Test Case : 6.4

**Comment by hammadhttps** [comment]
When admin  logged in and clicked manage category and clicks homepage it displays Whitelabel Error Page
Reference: Test Case 9.5

**Comment by faiq101** [comment]
When user clicks homepage it displays webpage error. 
Reference Test Case : 6.5

**Comment by HammadulHassan5812** [comment]
When admin logged in Admin logged in and clicked add product and miss some values it displays Display error message
Reference: Test Case 10.1

**Comment by HammadulHassan5812** [comment]
When admin logged in Admin logged in and clicked add product and Enter all values it displays Display adds product
Reference: Test Case 10.1

**Comment by hammadhttps** [comment]
When admin logged in and clicked manage category and clicks logout it displays Whitelabel Error Page
Reference: Test Case 11.2

**Comment by hammadhttps** [comment]
When admin logged in and clicked manage category and clicks homepage it displays Whitelabel Error Page
Reference: Test Case 11.3
